default_node_type_keys:
  "l3ls-evpn":
    spine:
      type: spine
      default_evpn_role: server
    l3leaf:
      type: l3leaf
      connected_endpoints: true
      default_evpn_role: client
      mlag_support: true
      network_services:
        l2: true
        l3: true
      vtep: true
    l2leaf:
      type: l2leaf
      connected_endpoints: true
      mlag_support: true
      network_services:
        l2: true
      underlay_router: false
      uplink_type: port-channel
    super_spine:
      type: super-spine
    overlay_controller:
      type: overlay-controller
      default_evpn_role: server
  "rt-media":
    leaf_blue:
      type: leaf_blue
      connected_endpoints: true
    leaf_purple:
      type: leaf_purple
      connected_endpoints: true
    leaf_red:
      type: leaf_red
      connected_endpoints: true
    spine_blue:
      type: spine_blue
      connected_endpoints: true
    spine_red:
      type: spine_red
      connected_endpoints: true