# Templates used by AVD eos_designs role
default_templates:
  # Templates defined per design
  l3ls-evpn:
    structured_config:
      # Render Structured Configuration
      # Base features
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.base"
        python_class_name: "AvdStructuredConfig"
      # MLAG feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.mlag"
        python_class_name: "AvdStructuredConfig"
      # Underlay feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.underlay"
        python_class_name: "AvdStructuredConfig"
      # Overlay feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.overlay"
        python_class_name: "AvdStructuredConfig"
      # Core Interfaces Feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.core_interfaces"
        python_class_name: "AvdStructuredConfig"
      # L3 Edge feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.l3_edge"
        python_class_name: "AvdStructuredConfig"
      # Network Services feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.network_services"
        python_class_name: "AvdStructuredConfig"
      # Connected Endpoints feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.connected_endpoints"
        python_class_name: "AvdStructuredConfig"
      # Inband Management feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.inband_management"
        python_class_name: "AvdStructuredConfig"
      # Merge custom_structured_configuration last
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.custom_structured_configuration"
        python_class_name: "AvdStructuredConfig"
        options:
          list_merge: "{{ custom_structured_configuration_list_merge }}"
    ip_addressing:
      router_id: 'ip_addressing/router-id-lastoctet.j2'
      mlag_ip_primary: 'ip_addressing/mlag-ip-primary-fixed.j2'
      mlag_ip_secondary: 'ip_addressing/mlag-ip-secondary-fixed.j2'
      mlag_l3_ip_primary: 'ip_addressing/mlag-l3-ip-primary-fixed.j2'
      mlag_l3_ip_secondary: 'ip_addressing/mlag-l3-ip-secondary-fixed.j2'
      p2p_uplinks_ip: 'ip_addressing/p2p-uplinks-ip.j2'
      p2p_uplinks_peer_ip: 'ip_addressing/p2p-uplinks-peer-ip.j2'
      vtep_ip_mlag: 'ip_addressing/vtep-ip-mlag.j2'
      vtep_ip: 'ip_addressing/vtep-ip.j2'
    # ip_addressing:
    #   python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.ip_addressing"
    #   python_class_name: "AvdIpAddressing"
    interface_descriptions:
      python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.interface_descriptions"
      python_class_name: "AvdInterfaceDescriptions"

  mpls:
    structured_config:
      # Render Structured Configuration
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.base"
        python_class_name: "AvdStructuredConfig"
      # Underlay feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.underlay"
        python_class_name: "AvdStructuredConfig"
      # Core Interfaces Feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.core_interfaces"
        python_class_name: "AvdStructuredConfig"
      # L3 Edge feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.l3_edge"
        python_class_name: "AvdStructuredConfig"
      # Connected Endpoints feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.connected_endpoints"
        python_class_name: "AvdStructuredConfig"
      # Overlay feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.overlay"
        python_class_name: "AvdStructuredConfig"
      # Network Services feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.network_services"
        python_class_name: "AvdStructuredConfig"
      # Merge custom_structured_configuration last
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.custom_structured_configuration"
        python_class_name: "AvdStructuredConfig"
        options:
          list_merge: "{{ custom_structured_configuration_list_merge }}"
    ip_addressing:
      python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.ip_addressing"
      python_class_name: "AvdIpAddressing"
    interface_descriptions:
      python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.interface_descriptions"
      python_class_name: "AvdInterfaceDescriptions"

  l2ls:
    structured_config:
      # Render Structured Configuration
      # Base features
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.base"
        python_class_name: "AvdStructuredConfig"
      # MLAG feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.mlag"
        python_class_name: "AvdStructuredConfig"
      # Underlay feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.underlay"
        python_class_name: "AvdStructuredConfig"
      # Core Interfaces Feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.core_interfaces"
        python_class_name: "AvdStructuredConfig"
      # L3 Edge feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.l3_edge"
        python_class_name: "AvdStructuredConfig"
      # Network Services feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.network_services"
        python_class_name: "AvdStructuredConfig"
      # Connected Endpoints feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.connected_endpoints"
        python_class_name: "AvdStructuredConfig"
      # Inband Management feature
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.inband_management"
        python_class_name: "AvdStructuredConfig"
      # Merge custom_structured_configuration last
      - python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.custom_structured_configuration"
        python_class_name: "AvdStructuredConfig"
        options:
          list_merge: "{{ custom_structured_configuration_list_merge }}"
    ip_addressing:
      python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.ip_addressing"
      python_class_name: "AvdIpAddressing"
    interface_descriptions:
      python_module: "ansible_collections.arista.avd.roles.eos_designs.python_modules.interface_descriptions"
      python_class_name: "AvdInterfaceDescriptions"
