# Project information
site_name: Arista AVD collection
site_author: Arista Ansible Team
site_description: Arista Validated Design collection's documentation
copyright: Copyright &copy; 2019 - 2022 Arista Networks

# Repository information
repo_name: AVD on Github
repo_url: https://github.com/aristanetworks/ansible-avd

# Configuration
use_directory_urls: false
edit_uri: edit/devel/ansible_collections/arista/avd/
theme:
  name: material
  # custom_dir: ansible_collections/arista/avd/docs/_overrides
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - header.autohide
    - content.code.annotate
    - content.tabs.link
  highlightjs: true
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book
    edit: fontawesome/solid/file-pen
  favicon: docs/_media/favicon.ico
  font:
    code: Fira Mono
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aristanetworks/ansible-avd
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AristaNetworks
    - icon: fontawesome/solid/globe
      link: https://www.arista.com

extra_css:
  - docs/stylesheets/extra.material.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - docs/stylesheets/tables.js

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date
  - exclude:
      glob:
        - molecule/*
        - tests/*

markdown_extensions:
  - admonition
  - attr_list
  - fontawesome_markdown
  - mdx_truly_sane_lists
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      base_path: 'ansible_collections/arista/avd/'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      separator: "-"
      permalink: true

# TOC
docs_dir: ansible_collections/arista/avd/
nav:
  - Home: README.md
  - Getting Started:
      - Introduction to Ansible and AVD: docs/getting-started/intro-to-ansible-and-avd.md
      - Example for Single DC L3LS: examples/single-dc-l3ls/README.md
      - Example for L2LS Fabric: examples/l2ls-fabric/README.md
      - Example for Campus Fabric: examples/campus-fabric/README.md
  - Installation:
      - Collection Installation: docs/installation/collection-installation.md
  - How-To:
      - Build Your First AVD Project: docs/how-to/first-project.md
      - Build Your First AVD & CVP Project: docs/how-to/first-cvp-avd-project.md
      - Use NAT Gateway With eAPI: docs/how-to/lab-with-nat.md
      - AWX & Tower Integration: docs/how-to/tower-integration.md
      - Configure ZTP Server With CVP Collection: docs/how-to/ztp.md
      - Setup Ansible AVD With VS Code Container: docs/how-to/vscode-container.md
  - Validation of Input Variables (BETA): docs/input-variable-validation-BETA.md
  - Roles Documentation:
      - eos_designs:
          - Overview: roles/eos_designs/README.md
          - Connected Endpoints: roles/eos_designs/doc/connected-endpoints.md
          - DCI & L3 Edge: roles/eos_designs/doc/l3-edge.md
          - Fabric Topology: roles/eos_designs/doc/fabric-topology.md
          - Fabric Variables: roles/eos_designs/doc/fabric-variables.md
          - Management Settings: roles/eos_designs/doc/management-settings.md
          - Network Services: roles/eos_designs/doc/network-services.md
          - PTP: roles/eos_designs/doc/ptp.md
          - Node Types: roles/eos_designs/doc/node-types.md
          - Platform Specific Settings: roles/eos_designs/doc/platform-settings.md
          - Custom Structured Configuration: roles/eos_designs/doc/custom-structured-configuration.md
          - MPLS Design (BETA):
              - Fabric Topology MPLS (BETA): roles/eos_designs/doc/fabric-topology-mpls-BETA.md
              - Fabric Variables MPLS (BETA): roles/eos_designs/doc/fabric-variables-mpls-BETA.md
              - Core Interfaces (BETA): roles/eos_designs/doc/core-interfaces-BETA.md
              - Network Services MPLS (BETA): roles/eos_designs/doc/network-services-mpls-BETA.md
              - Connected Endpoints MPLS (BETA): roles/eos_designs/doc/connected-endpoints-mpls-BETA.md
      - eos_cli_config_gen: roles/eos_cli_config_gen/README.md
      - cvp_configlet_upload: roles/cvp_configlet_upload/README.md
      - eos_config_deploy_cvp: roles/eos_config_deploy_cvp/README.md
      - eos_config_deploy_eapi: roles/eos_config_deploy_eapi/README.md
      - eos_validate_state: roles/eos_validate_state/README.md
      - eos_snapshot: roles/eos_snapshot/README.md
      - dhcp_provisioner: roles/dhcp_provisioner/README.md
      - build_output_folders: roles/build_output_folders/README.md
  - Modules Documentation:
      - Module Inventory to Containers: docs/modules/inventory_to_container.rst.md
      - Module Configlet Build Configuration: docs/modules/configlet_build_config.rst.md
      - AVD Plugins & Filters: plugins/README.md
      - CloudVision Module Documentation: https://cvp.avd.sh/
  - Contributing to AVD:
      - Overview: docs/contribution/overview.md
      - Setup Environment: docs/contribution/setup-environment.md
      - Git Installation: docs/contribution/setup-git.md
      - Getting Started: docs/contribution/getting-started.md
      - Code Style: docs/contribution/style-guide.md
      - Development Tips & Tricks: docs/contribution/development.md
  - External Resources:
      - Ansible Collection User Guide: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
      - Ansible User Guide: https://docs.ansible.com/ansible/latest/user_guide/index.html
  - Release Notes:
      - 3.x.x: docs/release-notes/3.x.x.md
      - 2.x.x: docs/release-notes/2.x.x.md
      - 1.1.x: docs/release-notes/1.1.x.md
      - 1.0.x: docs/release-notes/1.0.x.md
  - About:
      - AVD on Ansible Galaxy: https://galaxy.ansible.com/arista/avd
      - Arista CVP Collection: https://cvp.avd.sh/en/latest/
      - Arista Installation Script: https://github.com/arista-netdevops-community/avd-install
      - Arista NetDevOps Community: https://aristanetworks.github.io/netdevops-examples/
