router_bgp:
  as: '65200'
  router_id: 10.255.0.3
  bgp_defaults:
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      send_community: all
      maximum_routes: 0
      ebgp_multihop: 3
      next_hop_unchanged: true
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: none
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.0.31/24
    gateway: 192.168.0.1
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
ptp:
  mode: boundary
  priority1: 20
  priority2: 3
  domain: 127
  monitor:
    enabled: true
    threshold:
      offset_from_master: 250
      mean_path_delay: 1500
    missing_message:
      sequence_ids:
        enabled: true
        announce: 3
        delay_resp: 3
        follow_up: 3
        sync: 3
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 10.255.0.3/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 10.255.0.0/27 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
