router_bgp:
  as: '65001'
  router_id: 192.168.255.3
  bgp_defaults:
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      maximum_routes: 12000
      send_community: all
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  neighbors:
    192.168.0.0:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65000'
      description: UNDERLAY_FILTER_PEER_AS_SPINE1_Ethernet1
      route_map_out: RM-BGP-AS65000-OUT
    192.168.0.2:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65000'
      description: UNDERLAY_FILTER_PEER_AS_SPINE2_Ethernet1
      route_map_out: RM-BGP-AS65000-OUT
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
  MGMT:
    ip_routing: false
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
ethernet_interfaces:
  Ethernet1:
    peer: UNDERLAY_FILTER_PEER_AS_SPINE1
    peer_interface: Ethernet1
    peer_type: spine
    description: P2P_LINK_TO_UNDERLAY_FILTER_PEER_AS_SPINE1_Ethernet1
    shutdown: false
    mtu: 9000
    type: routed
    ip_address: 192.168.0.1/31
  Ethernet2:
    peer: UNDERLAY_FILTER_PEER_AS_SPINE2
    peer_interface: Ethernet1
    peer_type: spine
    description: P2P_LINK_TO_UNDERLAY_FILTER_PEER_AS_SPINE2_Ethernet1
    shutdown: false
    mtu: 9000
    type: routed
    ip_address: 192.168.0.3/31
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.255.3/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.254.3/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.255.0/24 eq 32
      20:
        action: permit 192.168.254.0/24 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  RM-BGP-AS65000-OUT:
    sequence_numbers:
      10:
        type: deny
        match:
        - as 65000
      20:
        type: permit
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:11:22:33:44:55
vxlan_interface:
  Vxlan1:
    description: UNDERLAY_FILTER_PEER_AS_L3LEAF1_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
