name: Test Installation
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  'setup':
    name: 'One liner installation'
    runs-on: ubuntu-20.04
    container: avdteam/base:3.8-v2.0
    steps:
      - uses: actions/checkout@v3
      - name: Execute one-liner installation
        run: |
          cd /tmp/
          curl -fs https://get.avd.sh | sh
      - name: Run Makefile commands
        run: |
          cd /tmp/arista-ansible/
          cat Makefile
          make
